generatorName: typescript-express-server
outputDir: samples/server/petstore/typescript-express-server
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-express-server
